package com.bigdata5.assignment1;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

import java.util.Arrays;

@SpringBootApplication
public class Assignment1Application {

	public static void main(String[] args) {
		SpringApplication.run(Assignment1Application.class, args);
	}


	/**
	 * Prints all the bean which are generated by spring boot on star-up up of application
	 * @param applicationContext
	 * @return
	 */
	@Bean
	public CommandLineRunner retrieveBeansCreatedBySpringBoot(ApplicationContext applicationContext){
		return args -> {

			String[] beanNames = applicationContext.getBeanDefinitionNames();

			Arrays.sort(beanNames);
			for (String name : beanNames) {
				// System.out.println("Bean is:  " +  name);
			}

		};
	}

}
